### ISSUE TITLE
Workflow Editor: Start/Stop gone after removing last job

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/joc-cockpit#17]
When removing the last Job in the workflow-editor, most of the time the Start and End Icons are gone and you cannot add a job anymore.

Workaround: Click on another workflow an click back.

Version 2.5.4

**Comment by ztka0054** [comment]
Hello @rfx77,

Thank you for your response.

I tried to reproduce the issue in my environment and found that it is related to the Workflow graph scrolling. 

Whenever you remove a job from a workflow the complete workflow graph is reloaded due to which sometimes the workflow moves out of the range of the scroller like:

![image](https://github.com/sos-berlin/joc-cockpit/assets/50707301/4d37bb01-bc26-487f-81e9-e530078f3c49)

But from the magnifying view at the right corner, you can see your workflow is there. To resolve this there are two workarounds:

1. Either you scroll top to get the magnifying glass in the workflow range
2. Click on the other workflow and click back.

Please let me know if my understanding of your issue is correct or not.

Thanks and best regards
Kanika Agrawal

**Comment by sosap** [comment]
The issue is confirmed and is tracked with

* [JOC-1588: Scroller in Configuration view should remain focused after removal of instructions](https://change.sos-berlin.com/browse/JOC-1588)

The fix will become available with releases 2.5.5 and 2.6.2.
