### ISSUE TITLE
after renaming of job-template link to workflows is lost

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/joc-cockpit#21]
After renaming a job-template the update-job button does not show any workflows anymore. in the workflow the name of the template is shown with the new name. 

the only way to solve this is to rerun the wizard of every dependent job in every workflow where the job-template is used

Version: 2.6.1 (Latest Patch)

**Comment by sosap** [comment]
The issue is confirmed and is tracked with

* [JOC-1590: Job Template reference should be considered after rename operation](https://change.sos-berlin.com/browse/JOC-1590)

The fix will become available for releases 2.5.5 and 2.6.2.

The issue occurs for deployed workflows, not for draft workflows. See issue description for a workaround.
