### ISSUE TITLE
old orders of renamed schedule stay in state "planned" and come back every day

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/joc-cockpit#24]
when i change the name of a schedule, the old orders with the old name are not removed from daily-plan even after restart of daily-plan-service. they stay in state "planned".

redeployment of all workflows does not help. 

i installed the latests patches ([JOC-1591](https://change.sos-berlin.com/browse/JOC-1591))

`joc_1         | JS7 entrypoint script: updating image
joc_1         | .. patch_api [INFO] extracting /var/sos-berlin.com/js7/joc/resources/joc/patches/js7_joc.2.6.1-PATCH.API-2.JOC-1586.JOC-1591.JOC-1592.jar -> /var/sos-berlin.com/js7/joc/webapps/joc/WEB-INF/classes
joc_1         | Archive:  /var/sos-berlin.com/js7/joc/resources/joc/patches/js7_joc.2.6.1-PATCH.API-2.JOC-1586.JOC-1591.JOC-1592.jar
joc_1         |   inflating: com/sos/joc/dailyplan/impl/DailyPlanOrdersGenerateImpl.class
joc_1         |   inflating: com/sos/joc/db/inventory/os/InventoryOperatingSystemsDBLayer.class
joc_1         |   inflating: com/sos/joc/inventory/impl/ReleaseResourceImpl$1.class
joc_1         |   inflating: com/sos/joc/inventory/impl/ReleaseResourceImpl.class
joc_1         | .. patch_api [INFO] no API patches available from .tar.gz files in directory: /var/sos-berlin.com/js7/joc/resources/joc/patches
joc_1         | .. patch_gui [INFO] applying GUI patch tarball: /var/sos-berlin.com/js7/joc/resources/joc/patches/js7_joc.2.6.1-PATCH.GUI-1.JOC-1585.tar.gz
`

![image](https://github.com/sos-berlin/joc-cockpit/assets/61699304/5ab3a234-b256-41a4-8820-e77d679f637c)

![image](https://github.com/sos-berlin/joc-cockpit/assets/61699304/5db3612b-41a4-4fd6-9f98-d5e174c3393c)

**Comment by rfx77** [comment]
The Problem seems to be that **i renamed the Schedule a**t some Point and so the association is lost. 

(i renamed the ticket and changed the text of my first post)

the old orders are planned under the schedule name: "/22_Windows/Windows.Sch.Logs.Collect" 
but the name of the schedule is now: "/22_Hosts/Hosts.Sch.Logs.Collect" 

**even after deletion** of the orders they are planned again by the daily-plan service.

how do i get rid of this orders?

**Comment by sosap** [comment]
Your observation is confirmed, orders remain in place in the Daily Plan after a schedule is renamed. This applies to both orders in planned and in submitted state and results in duplicate orders. This happens at the point in time when releasing a renamed schedule. This is unwanted behavior.

We cannot confirm the behavior that the Daily Plan Service will create orders for original versions of schedules that have been renamed and released. One reason being that a Daily Plan Service run will not add orders to dates for which orders exist. Another reason being that from our observation new Daily Plan dates populated by the Daily Plan Service will not make previous versions of a schedule resurrect.

This issue is tracked with

* [JOC-1599: Schedule reference should be considered after rename operation](https://change.sos-berlin.com/browse/JOC-1599)
